### ISSUE TITLE
Address Sanitizer issues in Everyplay

### ISSUE THREAD

**Issue by dannyNK** [Everyplay/everyplay-ios-sdk#36]
When running our game using the [address sanitizer](https://developer.apple.com/library/prerelease/content/documentation/DeveloperTools/Conceptual/debugging_with_xcode/chapters/special_debugging_workflows.html#//apple_ref/doc/uid/TP40015022-CH9-SW23) to help find memory issues, the game cannot progress past the Everyplay initialisation.

Output below

```
==3861==AddressSanitizer CHECK failed: /Library/Caches/com.apple.xbs/Sources/clang/clang-703.0.31/src/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:182 "((h->type == CommonInterceptorMetadata::CIMT_FILE)) != (0)" (0x0, 0x0)

    #0 0x1050a013f in __asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/var/containers/Bundle/Application/5BBB8B05-797E-4930-8E7E-BC5A7819B2D7/BTD Battles.app/Frameworks/libclang_rt.asan_ios_dynamic.dylib+0x4813f)

    #1 0x1050a486f in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/var/containers/Bundle/Application/5BBB8B05-797E-4930-8E7E-BC5A7819B2D7/BTD Battles.app/Frameworks/libclang_rt.asan_ios_dynamic.dylib+0x4c86f)

    #2 0x10508e87b in wrap_fclose (/var/containers/Bundle/Application/5BBB8B05-797E-4930-8E7E-BC5A7819B2D7/BTD Battles.app/Frameworks/libclang_rt.asan_ios_dynamic.dylib+0x3687b)

    #3 0x1018182c7 in +[EveryplayCommon isJailbroken] (/var/containers/Bundle/Application/5BBB8B05-797E-4930-8E7E-BC5A7819B2D7/BTD Battles.app/BTD Battles+0x10173c2c7)

    #4 0x1017f6677 in -[Everyplay init] (/var/containers/Bundle/Application/5BBB8B05-797E-4930-8E7E-BC5A7819B2D7/BTD Battles.app/BTD Battles+0x10171a677)

    #5 0x1017f658f in __27+[Everyplay sharedInstance]_block_invoke (/var/containers/Bundle/Application/5BBB8B05-797E-4930-8E7E-BC5A7819B2D7/BTD Battles.app/BTD Battles+0x10171a58f)

    #6 0x1060b1a3b in _dispatch_client_callout (/usr/lib/system/introspection/libdispatch.dylib+0x1a3b)

    #7 0x1060b28b3 in dispatch_once_f (/usr/lib/system/introspection/libdispatch.dylib+0x28b3)

    #8 0x1017f6563 in +[Everyplay sharedInstance] (/var/containers/Bundle/Application/5BBB8B05-797E-4930-8E7E-BC5A7819B2D7/BTD Battles.app/BTD Battles+0x10171a563)

    #9 0x1017faf57 in +[Everyplay setClientId:clientSecret:redirectURI:] (/var/containers/Bundle/Application/5BBB8B05-797E-4930-8E7E-BC5A7819B2D7/BTD Battles.app/BTD Battles+0x10171ef57)
```
This is running on an iPhone 6S Plus running iOS 9.3.2, using Xcode 7.3.1 to build.

To be able to run the game at all with the sanitiser on, the entire framework needs removed.

**Comment by paugit** [comment]
Thanks. Confirmed. This will get fixed in the next release.

**Comment by paugit** [comment]
This is fixed in latest Unity Everyplay 2120-1540 - Sep 12th 2016 release.
